### PR TITLE
merge upstream

### PR DESCRIPTION
**Pull request by ddbenson**
Hello @nicks, @ronpepsi, @nfelsen, 

Please review the following commits I made in branch 'ddb-sync-upstream'.

R=@nicks
R=@ronpepsi
R=@nfelsen

MANUAL TESTING=not manually tested

### CODE REVIEW

**Comment by ddbenson** [comment]
Not sure if this is the best way to merge upstream.  Appears all the documentation says to do it against master.  Creating a branch is the only way I think I can show the upstream work.

**Comment by nicks** [comment]
LGTM

ya...i always struggle with this. there's a trade-off between
1) merging origin/master changes on top -- highlights the upstream work, but buries our changes
2) rebasing on top of origin/master -- makes it hard to see what changed upstream, but keeps our changes on top

I tend to prefer (2), just because it makes it way easier to maintain long-lived forks. but i don't think the choice matters much here.

**Comment by ddbenson** [comment]
Ok,  I can totally do a rebase on origin/master if you want?

**Comment by nicks** [comment]
whatever, this fork is so simple, it doesn't matter

**Pull request merged**
